backend:
  name: github
  repo: kailbert/gatsby-netlify
  branch: master

media_folder: static/assets
public_folder: /assets

collections:
  - name: projects
    label: Projects
    folder: src/projects
    create: true
    fields:
      - {name: title, label: Title}
      - {name: date, label: Date, widget: date}
      - {name: videoid, label: VideoId, widget: string}
      - {name: client, label: ClientName, widget: string}
      - {name: body, label: Body, widget: markdown}
      - {name: image, label: Image, widget: image}
